"""
api/models/event.py
───────────────────
ORM model for the `analytics_events` table.

This is a high-volume append-only table. Events are never updated or deleted
in normal operation — they form an immutable audit trail.

`player_id` is intentionally nullable (no FK constraint) so events can be
recorded for guest/anonymous players without requiring a players row, and
so purging a player account does not cascade-delete their analytics history.

`properties` is JSONB to accommodate arbitrary event-specific payloads
without schema migrations as new event types are introduced.
"""

from __future__ import annotations

from uuid import UUID

from sqlalchemy import ForeignKey, String, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import Base, TimestampMixin


class AnalyticsEvent(Base, TimestampMixin):
    __tablename__ = "analytics_events"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Stable event identity, generated by Postgres.",
    )

    # ── Foreign keys ───────────────────────────────────────────────────────────
    session_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("sessions.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="The session this event belongs to. Nullable for pre-session or system events.",
    )
    # No FK constraint on player_id — see module docstring.
    player_id: Mapped[UUID | None] = mapped_column(
        nullable=True,
        index=True,
        doc="The player who triggered this event. No FK so purged players don't delete events.",
    )

    # ── Event classification ───────────────────────────────────────────────────
    event_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        index=True,
        doc="Dot-namespaced event identifier, e.g. 'session.started', 'player.joined'.",
    )

    # ── Payload ────────────────────────────────────────────────────────────────
    properties: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        doc="Arbitrary event-specific properties. Schema is event_type-dependent.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    session: Mapped["Session | None"] = relationship(  # noqa: F821
        "Session",
        lazy="select",
        foreign_keys=[session_id],
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<AnalyticsEvent id={self.id} type={self.event_type!r} "
            f"session={self.session_id} player={self.player_id}>"
        )
