"""
api/models/game.py
──────────────────
ORM model for the `games` table.

A Game is a registered title that authenticates with Nexus via its `api_key`.
The `config` JSONB column holds game-specific settings (e.g. default session
parameters, feature flags) without requiring schema changes as games evolve.
"""

from __future__ import annotations

from uuid import UUID

from sqlalchemy import ForeignKey, String, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import Base, TimestampMixin


class Game(Base, TimestampMixin):
    __tablename__ = "games"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Stable game identity, generated by Postgres.",
    )

    # ── Identity fields ────────────────────────────────────────────────────────
    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        doc="Human-readable game title.",
    )
    api_key: Mapped[str] = mapped_column(
        String(64),
        unique=True,
        nullable=False,
        index=True,
        doc="Secret API key issued to the game developer. Treat as a credential.",
    )

    # ── Ownership ──────────────────────────────────────────────────────────────
    owner_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("players.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="The player who registered this game. Nullable to survive player deletion.",
    )

    # ── Game configuration ─────────────────────────────────────────────────────
    config: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        doc="Arbitrary game-level configuration. Stored as JSONB for GIN indexing.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    owner: Mapped["Player"] = relationship(  # noqa: F821
        "Player",
        back_populates="games",
        lazy="select",
    )
    sessions: Mapped[list["Session"]] = relationship(  # noqa: F821
        "Session",
        back_populates="game",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Game id={self.id} name={self.name!r}>"
