"""
api/models/npc.py
─────────────────
ORM models for the `npcs` and `npc_interactions` tables.

These models define the *schema* for Phase 2 AI NPC features. Phase 1
creates the tables and relationships but no service logic touches them yet.
All JSONB columns that will carry AI state are defined here so the migration
is complete and forward-compatible.
"""

from __future__ import annotations

from uuid import UUID

from sqlalchemy import ForeignKey, String, Text, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import Base, TimestampMixin

# ── Memory scope values ────────────────────────────────────────────────────────
MEMORY_SCOPE_SESSION = "session"
MEMORY_SCOPE_PERSISTENT = "persistent"


class NPC(Base, TimestampMixin):
    """
    A stateful AI NPC instance bound to a specific session.

    `personality`, `secrets`, `initial_state`, and `current_state` are all
    JSONB to allow arbitrary AI-defined structures without schema migrations
    as NPC designs evolve in Phase 2.

    `memory_scope` controls whether NPC memory persists across sessions
    (persistent) or is wiped when the session ends (session).
    """

    __tablename__ = "npcs"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Stable NPC identity, generated by Postgres.",
    )

    # ── Foreign keys ───────────────────────────────────────────────────────────
    session_id: Mapped[UUID] = mapped_column(
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="The session this NPC is bound to.",
    )

    # ── NPC definition ─────────────────────────────────────────────────────────
    name: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        doc="Human-readable NPC name shown to players, e.g. 'Marcus Webb'.",
    )
    personality: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        doc="Structured personality descriptor fed to the LLM prompt in Phase 2.",
    )
    secrets: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        doc="Hidden information the NPC knows. Tracked for leak detection in Phase 2.",
    )

    # ── State ──────────────────────────────────────────────────────────────────
    initial_state: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        doc="Snapshot of the NPC's state at creation. Immutable after INSERT.",
    )
    current_state: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        doc="Live mutable NPC state. Updated by Phase 2 after each interaction.",
    )

    # ── Memory scope ───────────────────────────────────────────────────────────
    memory_scope: Mapped[str] = mapped_column(
        String(20),
        server_default=text("'session'"),
        nullable=False,
        doc="'session' = ephemeral memory; 'persistent' = survives across sessions.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    session: Mapped["Session"] = relationship(  # noqa: F821
        "Session",
        back_populates="npcs",
        lazy="select",
    )
    interactions: Mapped[list["NPCInteraction"]] = relationship(
        "NPCInteraction",
        back_populates="npc",
        lazy="select",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<NPC id={self.id} name={self.name!r} session={self.session_id}>"


class NPCInteraction(Base, TimestampMixin):
    """
    An immutable audit log entry for a single player↔NPC exchange.

    Every interaction captures the full before/after state so the AI's
    decision process is reproducible and auditable. `secret_leaked` records
    which secret key (if any) the NPC revealed during this exchange.
    """

    __tablename__ = "npc_interactions"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Stable interaction record identity.",
    )

    # ── Foreign keys ───────────────────────────────────────────────────────────
    npc_id: Mapped[UUID] = mapped_column(
        ForeignKey("npcs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    player_id: Mapped[UUID] = mapped_column(
        ForeignKey("players.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    session_id: Mapped[UUID] = mapped_column(
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        doc="Denormalised for fast per-session interaction queries without joining through npcs.",
    )

    # ── Interaction content ────────────────────────────────────────────────────
    player_message: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="The exact text the player sent to the NPC.",
    )
    npc_response: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        doc="The NPC's generated response.",
    )

    # ── State delta ────────────────────────────────────────────────────────────
    state_before: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        doc="NPC current_state snapshot immediately before this interaction.",
    )
    state_after: Mapped[dict] = mapped_column(
        JSONB,
        nullable=False,
        doc="NPC current_state snapshot immediately after this interaction.",
    )

    # ── AI behaviour metadata ─────────────────────────────────────────────────
    behaviour: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        doc="AI-classified behaviour tag, e.g. 'deflect', 'confess', 'mislead'.",
    )
    secret_leaked: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        doc="The key of the secret that was revealed, if any. Null = no leak.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    npc: Mapped["NPC"] = relationship(
        "NPC",
        back_populates="interactions",
        lazy="select",
    )
    player: Mapped["Player"] = relationship(  # noqa: F821
        "Player",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<NPCInteraction id={self.id} npc={self.npc_id} "
            f"player={self.player_id} behaviour={self.behaviour!r}>"
        )
