"""
api/models/player.py
────────────────────
ORM model for the `players` table.

Players are the top-level identity primitive in Nexus. Both registered
accounts and anonymous guest sessions share this table; `is_guest`
distinguishes them. Account lockout state lives here so auth queries
need only one table scan.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from sqlalchemy import Boolean, DateTime, Integer, String, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import Base, TimestampMixin


class Player(Base, TimestampMixin):
    __tablename__ = "players"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Stable player identity, generated by Postgres.",
    )

    # ── Identity fields ────────────────────────────────────────────────────────
    username: Mapped[str] = mapped_column(
        String(50),
        unique=True,
        nullable=False,
        index=True,
        doc="Unique display name chosen at registration.",
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        doc="Unique email address. Stored lower-cased by the application layer.",
    )
    password_hash: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        doc="bcrypt hash of the player's password. Never log or expose this.",
    )

    # ── Account type ───────────────────────────────────────────────────────────
    is_guest: Mapped[bool] = mapped_column(
        Boolean,
        server_default=text("FALSE"),
        nullable=False,
        doc="True for anonymous guest sessions created via POST /auth/guest.",
    )

    # ── Activity tracking ──────────────────────────────────────────────────────
    last_login: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        doc="Timestamp of the most recent successful login.",
    )

    # ── Security / lockout ─────────────────────────────────────────────────────
    is_locked: Mapped[bool] = mapped_column(
        Boolean,
        server_default=text("FALSE"),
        nullable=False,
        doc="Account locked after 5 consecutive failed login attempts.",
    )
    failed_login_count: Mapped[int] = mapped_column(
        Integer,
        server_default=text("0"),
        nullable=False,
        doc="Consecutive failed login attempts. Reset to 0 on successful auth.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    # back_populates counterparts are declared on the child models.
    games: Mapped[list["Game"]] = relationship(  # noqa: F821
        "Game",
        back_populates="owner",
        lazy="select",
    )
    session_players: Mapped[list["SessionPlayer"]] = relationship(  # noqa: F821
        "SessionPlayer",
        back_populates="player",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Player id={self.id} username={self.username!r} guest={self.is_guest}>"
