"""
api/models/session.py
─────────────────────
ORM models for the `sessions` and `session_players` tables.

`Session` is the core multiplayer room object. Its lifecycle is:
  created → active → ended

`SessionPlayer` is the join table between sessions and players, with
additional metadata (role, join/leave timestamps) making it a proper
association object rather than a bare many-to-many.
"""

from __future__ import annotations

from datetime import datetime
from uuid import UUID

from sqlalchemy import Boolean, DateTime, ForeignKey, Integer, String, text
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from api.models.base import Base, TimestampMixin

# ── Status literal values ──────────────────────────────────────────────────────
# Defined here rather than as a Postgres ENUM so the column can be queried
# with plain string comparisons without requiring ENUM type management in
# migrations when new statuses are introduced.
SESSION_STATUS_CREATED = "created"
SESSION_STATUS_ACTIVE = "active"
SESSION_STATUS_ENDED = "ended"


class Session(Base, TimestampMixin):
    __tablename__ = "sessions"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Stable session identity, generated by Postgres.",
    )

    # ── Foreign keys ───────────────────────────────────────────────────────────
    game_id: Mapped[UUID | None] = mapped_column(
        ForeignKey("games.id", ondelete="SET NULL"),
        nullable=True,
        index=True,
        doc="The game this session belongs to.",
    )

    # ── Session identity ───────────────────────────────────────────────────────
    join_code: Mapped[str] = mapped_column(
        String(12),
        unique=True,
        nullable=False,
        index=True,
        doc="Short human-typeable code: 'NEXUS-XXXX'. Unique across all active sessions.",
    )

    # ── Lifecycle ──────────────────────────────────────────────────────────────
    status: Mapped[str] = mapped_column(
        String(20),
        server_default=text("'created'"),
        nullable=False,
        index=True,
        doc="Lifecycle state: created | active | ended.",
    )
    ended_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        doc="Wall-clock time when the session moved to 'ended'. Null while live.",
    )

    # ── Capacity & routing ────────────────────────────────────────────────────
    max_players: Mapped[int] = mapped_column(
        Integer,
        server_default=text("4"),
        nullable=False,
        doc="Hard cap on concurrent players. Enforced by the join endpoint.",
    )
    region: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        doc="Deployment region tag, e.g. 'ap-south-1'. Used for routing hints.",
    )
    game_mode: Mapped[str | None] = mapped_column(
        String(50),
        nullable=True,
        doc="Game-defined mode string, e.g. 'interrogation'. Purely informational.",
    )

    # ── Access control ─────────────────────────────────────────────────────────
    is_locked: Mapped[bool] = mapped_column(
        Boolean,
        server_default=text("FALSE"),
        nullable=False,
        doc="When True, new players cannot join. Only the creator can set this.",
    )

    # ── Flexible storage ───────────────────────────────────────────────────────
    config: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        doc="Immutable session configuration set at creation time.",
    )
    state: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        doc="Mutable live game state. Updated via PATCH /sessions/{id}/state (shallow merge).",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    game: Mapped["Game"] = relationship(  # noqa: F821
        "Game",
        back_populates="sessions",
        lazy="select",
    )
    session_players: Mapped[list["SessionPlayer"]] = relationship(
        "SessionPlayer",
        back_populates="session",
        lazy="select",
        cascade="all, delete-orphan",
    )
    npcs: Mapped[list["NPC"]] = relationship(  # noqa: F821
        "NPC",
        back_populates="session",
        lazy="select",
        cascade="all, delete-orphan",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Session id={self.id} join_code={self.join_code!r} status={self.status!r}>"


class SessionPlayer(Base, TimestampMixin):
    """
    Association object between a Session and a Player.

    Using an explicit association object (rather than a bare many-to-many
    `Table`) lets us store per-membership metadata: role, join time,
    and the optional `left_at` that records when a player departed.
    A null `left_at` means the player is currently in the session.
    """

    __tablename__ = "session_players"

    # ── Primary key ────────────────────────────────────────────────────────────
    id: Mapped[UUID] = mapped_column(
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        doc="Stable membership record identity.",
    )

    # ── Foreign keys ───────────────────────────────────────────────────────────
    session_id: Mapped[UUID] = mapped_column(
        ForeignKey("sessions.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    player_id: Mapped[UUID] = mapped_column(
        ForeignKey("players.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )

    # ── Membership metadata ────────────────────────────────────────────────────
    # joined_at mirrors created_at semantically; we keep both for API clarity.
    # TimestampMixin provides `created_at`; we alias the intent here.
    joined_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=False),
        server_default=text("NOW()"),
        nullable=False,
        doc="When the player joined the session. Duplicates created_at intentionally for API clarity.",
    )
    left_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=False),
        nullable=True,
        doc="When the player left. Null = currently in session.",
    )
    role: Mapped[str] = mapped_column(
        String(20),
        server_default=text("'player'"),
        nullable=False,
        doc="Player role within the session: 'player' | 'host'. Extensible.",
    )

    # ── Relationships ──────────────────────────────────────────────────────────
    session: Mapped["Session"] = relationship(
        "Session",
        back_populates="session_players",
        lazy="select",
    )
    player: Mapped["Player"] = relationship(  # noqa: F821
        "Player",
        back_populates="session_players",
        lazy="select",
    )

    def __repr__(self) -> str:  # pragma: no cover
        return (
            f"<SessionPlayer session={self.session_id} "
            f"player={self.player_id} role={self.role!r} "
            f"left={self.left_at is not None}>"
        )
